# Form implementation generated from reading ui file 'clients_add_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_clients_addWidget(object):
    def setupUi(self, clients_addWidget):
        clients_addWidget.setObjectName("clients_addWidget")
        clients_addWidget.resize(400, 430)
        clients_addWidget.setAccessibleName("")
        clients_addWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        clients_addWidget.setStyleSheet("QWidget\n"
" {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 rgb(148, 87, 235), stop:1 rgb(87, 37, 138));\n"
"}")
        self.label_registr = QtWidgets.QLabel(parent=clients_addWidget)
        self.label_registr.setGeometry(QtCore.QRect(120, 10, 161, 51))
        self.label_registr.setStyleSheet("QLabel\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.label_registr.setObjectName("label_registr")
        self.lineEdit_NumberDogovor = QtWidgets.QLineEdit(parent=clients_addWidget)
        self.lineEdit_NumberDogovor.setGeometry(QtCore.QRect(40, 60, 311, 51))
        self.lineEdit_NumberDogovor.setStyleSheet("QLineEdit\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.lineEdit_NumberDogovor.setText("")
        self.lineEdit_NumberDogovor.setObjectName("lineEdit_NumberDogovor")
        self.lineEdit_FullName = QtWidgets.QLineEdit(parent=clients_addWidget)
        self.lineEdit_FullName.setGeometry(QtCore.QRect(40, 110, 311, 51))
        self.lineEdit_FullName.setStyleSheet("QLineEdit\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.lineEdit_FullName.setText("")
        self.lineEdit_FullName.setObjectName("lineEdit_FullName")
        self.lineEdit_Balance = QtWidgets.QLineEdit(parent=clients_addWidget)
        self.lineEdit_Balance.setGeometry(QtCore.QRect(40, 160, 311, 51))
        self.lineEdit_Balance.setStyleSheet("QLineEdit\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.lineEdit_Balance.setText("")
        self.lineEdit_Balance.setObjectName("lineEdit_Balance")
        self.lineEdit_PhoneNumber = QtWidgets.QLineEdit(parent=clients_addWidget)
        self.lineEdit_PhoneNumber.setGeometry(QtCore.QRect(40, 210, 311, 51))
        self.lineEdit_PhoneNumber.setStyleSheet("QLineEdit\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.lineEdit_PhoneNumber.setText("")
        self.lineEdit_PhoneNumber.setObjectName("lineEdit_PhoneNumber")
        self.lineEdit_Email = QtWidgets.QLineEdit(parent=clients_addWidget)
        self.lineEdit_Email.setGeometry(QtCore.QRect(40, 260, 311, 51))
        self.lineEdit_Email.setStyleSheet("QLineEdit\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.lineEdit_Email.setText("")
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.lineEdit_Address = QtWidgets.QLineEdit(parent=clients_addWidget)
        self.lineEdit_Address.setGeometry(QtCore.QRect(40, 310, 311, 51))
        self.lineEdit_Address.setStyleSheet("QLineEdit\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.lineEdit_Address.setText("")
        self.lineEdit_Address.setObjectName("lineEdit_Address")
        self.push_add_saveClient = QtWidgets.QPushButton(parent=clients_addWidget)
        self.push_add_saveClient.setGeometry(QtCore.QRect(140, 360, 121, 50))
        self.push_add_saveClient.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 50);; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: #8e44ad;\n"
"}")
        self.push_add_saveClient.setObjectName("push_add_saveClient")

        self.retranslateUi(clients_addWidget)
        QtCore.QMetaObject.connectSlotsByName(clients_addWidget)

    def retranslateUi(self, clients_addWidget):
        _translate = QtCore.QCoreApplication.translate
        clients_addWidget.setWindowTitle(_translate("clients_addWidget", "Клиенты"))
        self.label_registr.setText(_translate("clients_addWidget", "Новая колонка"))
        self.lineEdit_NumberDogovor.setPlaceholderText(_translate("clients_addWidget", "Номер договора"))
        self.lineEdit_FullName.setPlaceholderText(_translate("clients_addWidget", "ФИО"))
        self.lineEdit_Balance.setPlaceholderText(_translate("clients_addWidget", "Баланс"))
        self.lineEdit_PhoneNumber.setPlaceholderText(_translate("clients_addWidget", "Номер телефона"))
        self.lineEdit_Email.setPlaceholderText(_translate("clients_addWidget", "Электронная почта"))
        self.lineEdit_Address.setPlaceholderText(_translate("clients_addWidget", "Адрес"))
        self.push_add_saveClient.setText(_translate("clients_addWidget", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    clients_addWidget = QtWidgets.QWidget()
    ui = Ui_clients_addWidget()
    ui.setupUi(clients_addWidget)
    clients_addWidget.show()
    sys.exit(app.exec())
