# Form implementation generated from reading ui file 'error_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_error_widget(object):
    def setupUi(self, error_widget):
        error_widget.setObjectName("error_widget")
        error_widget.resize(468, 167)
        error_widget.setAccessibleName("")
        error_widget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        error_widget.setStyleSheet("QWidget\n"
" {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 rgb(148, 87, 235), stop:1 rgb(87, 37, 138));\n"
"}")
        self.label_error = QtWidgets.QLabel(parent=error_widget)
        self.label_error.setGeometry(QtCore.QRect(180, 10, 120, 50))
        self.label_error.setStyleSheet("QLabel\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.label_error.setObjectName("label_error")
        self.label_text_error = QtWidgets.QLabel(parent=error_widget)
        self.label_text_error.setGeometry(QtCore.QRect(10, 60, 450, 91))
        self.label_text_error.setStyleSheet("QLabel\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.label_text_error.setText("")
        self.label_text_error.setObjectName("label_text_error")

        self.retranslateUi(error_widget)
        QtCore.QMetaObject.connectSlotsByName(error_widget)

    def retranslateUi(self, error_widget):
        _translate = QtCore.QCoreApplication.translate
        error_widget.setWindowTitle(_translate("error_widget", "Ошибка"))
        self.label_error.setText(_translate("error_widget", "Ошибка!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    error_widget = QtWidgets.QWidget()
    ui = Ui_error_widget()
    ui.setupUi(error_widget)
    error_widget.show()
    sys.exit(app.exec())
