# Form implementation generated from reading ui file 'zaits.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 451)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 rgb(148, 87, 235), stop:1 rgb(87, 37, 138));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(0, 50, 640, 351))
        self.tableView.setStyleSheet("/* Стиль для QTableView */\n"
"QTableView {\n"
"    border: 2px solid #9b59b6; /* Фиолетовая рамка */\n"
"    border-radius: 4px;\n"
"    background-color: #ecf0f1; /* Светло-серый цвет фона */\n"
"    gridline-color: #bdc3c7; /* Цвет линий сетки */\n"
"    selection-background-color: #9b59b6; /* Фиолетовый цвет выделенных ячеек */\n"
"}\n"
"\n"
"/* Стиль для заголовка QTableView */\n"
"QHeaderView::section {\n"
"    background-color: #9b59b6; /* Фиолетовый цвет фона заголовка */\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: 1px solid #9b59b6; /* Фиолетовая рамка заголовка */\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Стиль для выделенной строки в QTableView */\n"
"QTableView QTableCornerButton::section {\n"
"    background-color: #9b59b6; /* Фиолетовый цвет фона выделенной строки */\n"
"    border: 1px solid #9b59b6; /* Фиолетовая рамка выделенной строки */\n"
"    border-radius: 4px;\n"
"}")
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.label_account = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_account.setGeometry(QtCore.QRect(590, 0, 51, 51))
        self.label_account.setStyleSheet("/* Стиль для QPushButton */\n"
"QLabel {\n"
"    background-color: #9b59b6; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"")
        self.label_account.setText("")
        self.label_account.setPixmap(QtGui.QPixmap("free-icon-administrator-560321.png"))
        self.label_account.setScaledContents(True)
        self.label_account.setObjectName("label_account")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 400, 631, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_undertable = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_undertable.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_undertable.setObjectName("horizontalLayout_undertable")
        self.pushButton_add_table = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_add_table.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: #9b59b6; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("free-icon-add-square-outlined-interface-button-54731.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_add_table.setIcon(icon)
        self.pushButton_add_table.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_add_table.setObjectName("pushButton_add_table")
        self.horizontalLayout_undertable.addWidget(self.pushButton_add_table)
        self.pushButton_delete_table = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_delete_table.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: #9b59b6; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_delete_table.setIcon(icon1)
        self.pushButton_delete_table.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_delete_table.setObjectName("pushButton_delete_table")
        self.horizontalLayout_undertable.addWidget(self.pushButton_delete_table)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 591, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_ontable = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_ontable.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_ontable.setObjectName("horizontalLayout_ontable")
        self.pushButton_table = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_table.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: #9b59b6; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("free-icon-table-103091.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_table.setIcon(icon2)
        self.pushButton_table.setIconSize(QtCore.QSize(32, 35))
        self.pushButton_table.setAutoDefault(False)
        self.pushButton_table.setObjectName("pushButton_table")
        self.horizontalLayout_ontable.addWidget(self.pushButton_table)
        self.pushButton_analysis = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton_analysis.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.pushButton_analysis.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: #9b59b6; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("free-icon-analysis-1260079.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_analysis.setIcon(icon3)
        self.pushButton_analysis.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_analysis.setObjectName("pushButton_analysis")
        self.horizontalLayout_ontable.addWidget(self.pushButton_analysis)
        self.pyshbutton_info = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pyshbutton_info.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.pyshbutton_info.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: #9b59b6; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("free-icon-info-943933.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pyshbutton_info.setIcon(icon4)
        self.pyshbutton_info.setIconSize(QtCore.QSize(32, 32))
        self.pyshbutton_info.setObjectName("pyshbutton_info")
        self.horizontalLayout_ontable.addWidget(self.pyshbutton_info)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_add_table.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_delete_table.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_table.setText(_translate("MainWindow", "Таблицы"))
        self.pushButton_analysis.setText(_translate("MainWindow", "Анализ"))
        self.pyshbutton_info.setText(_translate("MainWindow", "Информация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
