# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_registration_form(object):
    def setupUi(self, registration_form):
        registration_form.setObjectName("registration_form")
        registration_form.resize(400, 407)
        registration_form.setAccessibleName("")
        registration_form.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        registration_form.setStyleSheet("QWidget\n"
" {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 rgb(148, 87, 235), stop:1 rgb(87, 37, 138));\n"
"}")
        self.layoutWidget = QtWidgets.QWidget(parent=registration_form)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 280, 261, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.push_registration = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.push_registration.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 50);; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: #8e44ad;\n"
"}")
        self.push_registration.setObjectName("push_registration")
        self.verticalLayout.addWidget(self.push_registration)
        self.push_login = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.push_login.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 50);; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: #8e44ad;\n"
"}")
        self.push_login.setObjectName("push_login")
        self.verticalLayout.addWidget(self.push_login)
        self.label_registr = QtWidgets.QLabel(parent=registration_form)
        self.label_registr.setGeometry(QtCore.QRect(130, 10, 141, 51))
        self.label_registr.setStyleSheet("QLabel\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.label_registr.setObjectName("label_registr")
        self.lineEdit_mailregist = QtWidgets.QLineEdit(parent=registration_form)
        self.lineEdit_mailregist.setGeometry(QtCore.QRect(40, 170, 311, 51))
        self.lineEdit_mailregist.setStyleSheet("QLineEdit\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.lineEdit_mailregist.setText("")
        self.lineEdit_mailregist.setObjectName("lineEdit_mailregist")
        self.lineEdit_nameuser = QtWidgets.QLineEdit(parent=registration_form)
        self.lineEdit_nameuser.setGeometry(QtCore.QRect(40, 70, 311, 51))
        self.lineEdit_nameuser.setStyleSheet("QLineEdit\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.lineEdit_nameuser.setText("")
        self.lineEdit_nameuser.setObjectName("lineEdit_nameuser")
        self.lineEdit_passwordregistr = QtWidgets.QLineEdit(parent=registration_form)
        self.lineEdit_passwordregistr.setGeometry(QtCore.QRect(40, 220, 311, 51))
        self.lineEdit_passwordregistr.setStyleSheet("QLineEdit\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.lineEdit_passwordregistr.setText("")
        self.lineEdit_passwordregistr.setObjectName("lineEdit_passwordregistr")
        self.lineEdit_fullname = QtWidgets.QLineEdit(parent=registration_form)
        self.lineEdit_fullname.setGeometry(QtCore.QRect(40, 120, 311, 51))
        self.lineEdit_fullname.setStyleSheet("QLineEdit\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.lineEdit_fullname.setText("")
        self.lineEdit_fullname.setObjectName("lineEdit_fullname")

        self.retranslateUi(registration_form)
        QtCore.QMetaObject.connectSlotsByName(registration_form)

    def retranslateUi(self, registration_form):
        _translate = QtCore.QCoreApplication.translate
        registration_form.setWindowTitle(_translate("registration_form", "Регистрация"))
        self.push_registration.setText(_translate("registration_form", "Зарегистрироваться"))
        self.push_login.setText(_translate("registration_form", "Войти"))
        self.label_registr.setText(_translate("registration_form", "Регистрация"))
        self.lineEdit_mailregist.setPlaceholderText(_translate("registration_form", "Почта:"))
        self.lineEdit_nameuser.setPlaceholderText(_translate("registration_form", "Имя пользователя"))
        self.lineEdit_passwordregistr.setPlaceholderText(_translate("registration_form", "Пароль:"))
        self.lineEdit_fullname.setPlaceholderText(_translate("registration_form", "ФИО"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registration_form = QtWidgets.QWidget()
    ui = Ui_registration_form()
    ui.setupUi(registration_form)
    registration_form.show()
    sys.exit(app.exec())
