# Form implementation generated from reading ui file 'tablebut.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tablewidgetadd_form(object):
    def setupUi(self, tablewidgetadd_form):
        tablewidgetadd_form.setObjectName("tablewidgetadd_form")
        tablewidgetadd_form.resize(392, 347)
        tablewidgetadd_form.setAccessibleName("")
        tablewidgetadd_form.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        tablewidgetadd_form.setStyleSheet("QWidget\n"
" {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 rgb(148, 87, 235), stop:1 rgb(87, 37, 138));\n"
"}")
        self.label_tables = QtWidgets.QLabel(parent=tablewidgetadd_form)
        self.label_tables.setGeometry(QtCore.QRect(140, 0, 111, 51))
        self.label_tables.setStyleSheet("QLabel\n"
" {\n"
"    background-color: rgba(255, 255, 255, 50); /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"")
        self.label_tables.setObjectName("label_tables")
        self.pusg_agreements = QtWidgets.QPushButton(parent=tablewidgetadd_form)
        self.pusg_agreements.setGeometry(QtCore.QRect(100, 210, 191, 50))
        self.pusg_agreements.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 50);; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: #8e44ad;\n"
"}")
        self.pusg_agreements.setObjectName("pusg_agreements")
        self.push_staff = QtWidgets.QPushButton(parent=tablewidgetadd_form)
        self.push_staff.setGeometry(QtCore.QRect(100, 280, 193, 50))
        self.push_staff.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 50);; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: #8e44ad;\n"
"}")
        self.push_staff.setObjectName("push_staff")
        self.push_services = QtWidgets.QPushButton(parent=tablewidgetadd_form)
        self.push_services.setGeometry(QtCore.QRect(100, 160, 191, 50))
        self.push_services.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 50);; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: #8e44ad;\n"
"}")
        self.push_services.setObjectName("push_services")
        self.push_serviceTypes = QtWidgets.QPushButton(parent=tablewidgetadd_form)
        self.push_serviceTypes.setGeometry(QtCore.QRect(100, 110, 193, 50))
        self.push_serviceTypes.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 50);; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: #8e44ad;\n"
"}")
        self.push_serviceTypes.setObjectName("push_serviceTypes")
        self.push_clients = QtWidgets.QPushButton(parent=tablewidgetadd_form)
        self.push_clients.setGeometry(QtCore.QRect(100, 60, 193, 50))
        self.push_clients.setStyleSheet("/* Стиль для QPushButton */\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 50);; /* Фиолетовый цвет фона */\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    font-size: 16px;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"    border-radius: 4px; /* Закругленные углы */\n"
"}\n"
"\n"
"/* Стиль для QPushButton при наведении */\n"
"QPushButton:hover {\n"
"    background-color: #8e44ad;\n"
"}")
        self.push_clients.setObjectName("push_clients")

        self.retranslateUi(tablewidgetadd_form)
        QtCore.QMetaObject.connectSlotsByName(tablewidgetadd_form)

    def retranslateUi(self, tablewidgetadd_form):
        _translate = QtCore.QCoreApplication.translate
        tablewidgetadd_form.setWindowTitle(_translate("tablewidgetadd_form", "Таблицы"))
        self.label_tables.setText(_translate("tablewidgetadd_form", "Таблицы"))
        self.pusg_agreements.setText(_translate("tablewidgetadd_form", "Договоры"))
        self.push_staff.setText(_translate("tablewidgetadd_form", "Сотрудники"))
        self.push_services.setText(_translate("tablewidgetadd_form", "Сервисы"))
        self.push_serviceTypes.setText(_translate("tablewidgetadd_form", "Типы сервисов"))
        self.push_clients.setText(_translate("tablewidgetadd_form", "Клиенты"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tablewidgetadd_form = QtWidgets.QWidget()
    ui = Ui_tablewidgetadd_form()
    ui.setupUi(tablewidgetadd_form)
    tablewidgetadd_form.show()
    sys.exit(app.exec())
